export const REASONS_REQUEST = 'REASONS_REQUEST'
export const REASONS_SUCCESS = 'REASONS_SUCCESS'
export const REASONS_FAIL = 'REASONS_FAIL'

export const HISTORY_REQUEST = 'HISTORY_REQUEST'
export const HISTORY_SUCCESS = 'HISTORY_SUCCESS'
export const HISTORY_FAIL = 'HISTORY_FAIL'

export const ALLERGIES_REQUEST = 'ALLERGIES_REQUEST'
export const ALLERGIES_SUCCESS = 'ALLERGIES_SUCCESS'
export const ALLERGIES_FAIL = 'ALLERGIES_FAIL'