export const SECTIONS_REQUEST = 'SECTIONS_REQUEST';
export const SECTIONS_SUCCESS = 'SECTIONS_SUCCESS';
export const SECTIONS_FAIL    = 'SECTIONS_FAIL';

export const CATEGORY_LOOKUP_REQUEST = 'CATEGORY_LOOKUP_REQUEST';
export const CATEGORY_LOOKUP_SUCCESS = 'CATEGORY_LOOKUP_SUCCESS';
export const CATEGORY_LOOKUP_FAIL    = 'CATEGORY_LOOKUP_FAIL';